# -*- coding: utf-8 -*-
lines = []
lines.append("import express from \"express\";")
lines.append("import path from \"path\";")
lines.append("import dotenv from \"dotenv\";")
lines.append("import { createServer as createViteServer } from \"vite\";")
lines.append("")
lines.append("dotenv.config();")
lines.append("")
lines.append("const app = express();")
lines.append("const PORT = 3000;")
lines.append("")
lines.append("app.use(express.json({ limit: \"10mb\" }));")
lines.append("")
lines.append("// Local Dictionary")
lines.append('const LOCAL_DICT = {')
lines.append('  "ubiquitous": {"word":"ubiquitous","phonetic":"/ju0254u02d0u02c8bu026aku026atu0259s/","pos":"adj.","chineseDefinition":"无处不在的","englishDefinition":"Present everywhere.","rootAffix":"词根 ubique","memoryHook":"谐音: you-be-quite-us","phrases":["ubiquitous technology"],"sentences":[{"en":"Smartphones are ubiquitous.","zh":"智能手机无处不在。"}]},')
lines.append('  "ephemeral": {"word":"ephemeral","phonetic":"/u026au02c8femu0259ru0259l/","pos":"adj.","chineseDefinition":"短暂的","englishDefinition":"Lasting briefly."},')
lines.append('  "eloquent": {"word":"eloquent","phonetic":"/u02c8elu0259kwu0259nt/","pos":"adj.","chineseDefinition":"口才好的","englishDefinition":"Fluent and persuasive."},')
lines.append('  "pragmatic": {"word":"pragmatic","phonetic":"/pru00e6u0261u02c8mu00e6tu026ak/","pos":"adj.","chineseDefinition":"务实的"},')
lines.append('  "resilient": {"word":"resilient","phonetic":"/ru026au02c8zu026aliu0259nt/","pos":"adj.","chineseDefinition":"有韧性的"},')
lines.append('  "ambiguous": {"word":"ambiguous","phonetic":"/u00e6mu02c8bu026au0261ju0259s/","pos":"adj.","chineseDefinition":"模棱两可的"},')
lines.append('  "serendipity": {"word":"serendipity","phonetic":"/u02ccseru0259nu02c8du026apu0259ti/","pos":"n.","chineseDefinition":"意外发现"}')
lines.append("};")
lines.append("")
lines.append("function lookupLocal(word) { return LOCAL_DICT[(word||\"\").trim().toLowerCase()] || null; }")
lines.append("")
lines.append("// DeepSeek API")
lines.append("async function callDeepSeek(prompt, systemPrompt) {")
lines.append("  const apiKey = process.env.DEEPSEEK_API_KEY;")
lines.append("  if (!apiKey) throw new Error('DEEPSEEK_API_KEY not set');")
lines.append("  const controller = new AbortController();")
lines.append("  const timeout = setTimeout(() => controller.abort(), 10000);")
lines.append("  try {")
lines.append('    const resp = await fetch("https://api.deepseek.com/v1/chat/completions", {')
lines.append('      method: "POST",')
lines.append('      headers: { "Content-Type": "application/json", "Authorization": "Bearer " + apiKey },')
lines.append("      body: JSON.stringify({")
lines.append('        model: "deepseek-chat",')
lines.append("        messages: [")
lines.append("          { role: \"system\", content: systemPrompt },")
lines.append("          { role: \"user\", content: prompt }")
lines.append("        ],")
lines.append('        response_format: { type: "json_object" },')
lines.append("        temperature: 0.3,")
lines.append("        max_tokens: 2048,")
lines.append("      }),")
lines.append("      signal: controller.signal,")
lines.append("    });")
lines.append("    if (!resp.ok) { throw new Error('DeepSeek ' + resp.status + ': ' + (await resp.text())); }")
lines.append("    const data = await resp.json();")
lines.append("    return data.choices?.[0]?.message?.content || '';")
lines.append("  } finally { clearTimeout(timeout); }")
lines.append("}")
lines.append("")
lines.append("// Word Details API")
lines.append('app.post("/api/words/details", async (req, res) => {')
lines.append("  try {")
lines.append("    const { word, context } = req.body;")
lines.append('    if (!word || typeof word !== "string" || word.trim() === "") {')
lines.append('      return res.status(400).json({ error: "Word required" });')
lines.append("    }")
lines.append("    const local = lookupLocal(word);")
lines.append("    if (local) return res.json(local);")
lines.append("    try {")
lines.append("      let prompt = 'Provide vocabulary details for the English word: \"' + word.trim() + '\"';")
lines.append("      if (context) prompt += ' Context: \"' + context + '\"';")
lines.append("      prompt += '. Return a valid JSON object with keys: word, phonetic, pos, chineseDefinition, englishDefinition, rootAffix, memoryHook, phrases (array), sentences (array of objects with en and zh).';")
lines.append('      const result = await callDeepSeek(prompt, "You are a bilingual lexicographer. Respond ONLY with valid JSON.");')
lines.append("      if (result) {")
lines.append("        try {")
lines.append("          const data = JSON.parse(result);")
lines.append("          return res.json(data);")
lines.append("        } catch (e) {}")
lines.append("      }")
lines.append("    } catch (e) { console.warn('AI failed:', e.message); }")
lines.append("    return res.json({ word: word.trim(), phonetic: '', pos: '', chineseDefinition: '', englishDefinition: '', rootAffix: '', memoryHook: '', phrases: [], sentences: [] });")
lines.append("  } catch (error) { console.error(error); return res.status(500).json({ error: error.message }); }")
lines.append("});")
lines.append("")
lines.append("// Word Extraction API")
lines.append('app.post("/api/words/extract", async (req, res) => {')
lines.append("  try {")
lines.append("    const { text: inputText, userLevel } = req.body;")
lines.append('    if (!inputText || typeof inputText !== "string" || inputText.trim() === "") {')
lines.append('      return res.status(400).json({ error: "Text required" });')
lines.append("    }")
lines.append("    try {")
lines.append("      const prompt = 'Extract 5-12 difficult English words from this text for a ' + (userLevel || 'CET-6') + ' learner. Ignore easy words. Return JSON with: candidates (array of objects with word, contextSentence, quickTranslation, difficultyLevel). Text: ' + inputText.substring(0, 3000);")
lines.append('      const result = await callDeepSeek(prompt, "You are an ESL teacher. Return valid JSON only.");')
lines.append("      if (result) { try { return res.json(JSON.parse(result)); } catch(e) {} }")
lines.append("    } catch (e) { console.warn('AI extraction failed:', e.message); }")
lines.append("    const words = inputText.match(/[a-zA-Z]{5,}/g) || [];")
lines.append("    const unique = [...new Set(words.map(w => w.toLowerCase()))].slice(0, 10);")
lines.append("    return res.json({ candidates: unique.map(w => ({ word: w, contextSentence: inputText.substring(0, 100) + '...', quickTranslation: '[AI不可用]', difficultyLevel: 'Unknown' })) });")
lines.append("  } catch (error) { console.error(error); return res.status(500).json({ error: error.message }); }")
lines.append("});")
lines.append("")
lines.append("// Boot")
lines.append("async function boot() {")
lines.append('  if (process.env.NODE_ENV !== "production") {')
lines.append("    const vite = await createViteServer({ server: { middlewareMode: true }, appType: 'spa' });")
lines.append("    app.use(vite.middlewares);")
lines.append('    console.log("Vite dev middleware loaded.");')
lines.append("  } else {")
lines.append('    const distPath = path.join(process.cwd(), "dist");')
lines.append("    app.use(express.static(distPath));")
lines.append('    app.get("*", (req, res) => res.sendFile(path.join(distPath, "index.html")));')
lines.append("  }")
lines.append('  app.listen(PORT, "0.0.0.0", () => console.log("Server on http://0.0.0.0:" + PORT));')
lines.append("}")
lines.append("")
lines.append("boot().catch(console.error);")

with open("D:\\codex\\WordTrail\\-WordTrail-main\\server.ts", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("Server.ts written with", len(lines), "lines")
